name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: |
          pip install '.[dev]'
      - name: black
        uses: psf/black@24.8.0  # last release that supports 3.8 
        with:
          use_pyproject: false
      - name: mypy
        uses: tsuyoshicho/action-mypy@v3.9.3
        with:
          target: fulcrum/
          reporter: github-pr-check
          level: error
          tool_name: mypy
